echo "================================================================="
echo "Summary of the configuration"
echo "================================================================="
echo "Website Name: ${siteName}"
echo "-----------------------------------------------------------------"
echo "================================================================="
echo "MYSQL"
echo "-----------------------------------------------------------------"
echo "superUser: root"
echo "password: ${rootPassword}"
echo "-----------------------------------------------------------------"
echo "databse Wordpress: ${dbName}"
echo "database User Wordpress: ${dbUser}"
echo "database passWord Wordpress: ${userPassword}"
echo "================================================================="
echo "Wordpress"
echo "-----------------------------------------------------------------"
echo "Admin website: ${wpName}"
echo "password: ${wpPassword}"
echo "Email admin: ${wpEmail}"
echo "================================================================="


